/**
 * Seed-Workspace: Müller Bau GmbH (Bauunternehmer).
 *
 * Reiches Demo-Set für die VOB/B-Welt. 4 Projekte mit unterschiedlichen
 * Lifecycle-Ständen (Geplant → Bauphase → Abnahme → Gewährleistung) plus
 * volles Set an Folgedaten (NUs + Compliance, Nachträge, Sicherheiten,
 * Anzeigen, Mängel, Stunden, Material, Ausgangsrechnungen).
 */
import { db } from "../index";
import { serializeDisciplines } from "@/lib/workspace/disciplines";
import {
  workspaces,
  users,
  projects,
  contracts,
  subcontractors,
  subcontractorCertificates,
  nachtraege,
  securities,
  projectContacts,
  fristen,
  bautagebuchEntries,
  anzeigen,
  maengel,
  maengelAnzeigen,
  abnahmen,
  ausgangsrechnungen,
  ausgangsrechnungPositionen,
  ausgangsrechnungMahnungen,
  rechnungen,
  rechnungPositionen,
  rechnungAnomalien,
  mitarbeiter,
  stunden,
  meilensteine,
  sachverstaendige,
  vorgaenge,
  vorgangDocuments,
  vorgangAnalysisSteps,
  vorgangCitations,
  vorgangDrafts,
  vorgangLinks,
  vorgangAuditLog,
  queries,
} from "../schema";
import { isoPlus, dateAgo, dateAgoH, eur } from "./lib";

export const WS_ID = "ws_mueller_bau";
const USER_GF = "u_mueller_thomas";
const USER_POLIER = "u_mueller_klaus";
const USER_BUCH = "u_mueller_sandra";

export async function seedMuellerWorkspace(): Promise<void> {
  console.log("→ Workspace: Müller Bau GmbH (Bauunternehmer)");

  await db.insert(workspaces).values({
    id: WS_ID,
    name: "Müller Bau GmbH",
    tier: "team",
    workspaceRole: "bauunternehmer",
    // Hochbau-BU mit gemischtem Auftraggeberkreis. Disziplinen sind orthogonal:
    // ein BU "wählt" hier seine Bauschwerpunkte (Hochbau / Schlüsselfertig),
    // damit Vorlagen und Vertrags-Risiko-Heuristiken passen.
    disciplinesJson: serializeDisciplines(["hochbau_objektplanung"]),
    disciplineSubprofile: "custom",
    clientFocus: "gemischt",
    companySize: 28,
    vobLicenseStatus: "active",
    vobValidUntil: "2027-03-31",
    vobLicenseProvider: "din_media",
    bauabzugPflichtig: true,
    iban: "DE00100000000000000001",
    bic: "COBADEFFXXX",
    bankName: "Commerzbank Köln",
    taxId: "000/0000/0001",
    vatId: "DE100000001",
    address: "Müller Bau GmbH · Industriestr. 24 · 51149 Köln",
    email: "info@muellerbau.de",
    phone: "+49 30 0000-0001",
    datevBeraterNr: 1234567,
    datevMandantNr: 42001,
    datevKontenrahmen: "skr04",
  });

  await db.insert(users).values([
    {
      id: USER_GF,
      workspaceId: WS_ID,
      name: "Thomas Müller",
      email: "t.mueller@muellerbau.de",
      role: "admin",
      memberRole: "gf",
      roleLabel: "Geschäftsleitung",
      hasLicense: true,
      lastLoginAt: new Date(),
    },
    {
      id: USER_POLIER,
      workspaceId: WS_ID,
      name: "Klaus Schmidt",
      email: "k.schmidt@muellerbau.de",
      role: "user",
      memberRole: "polier",
      roleLabel: "Polier · BV-2024-014",
      hasLicense: true,
      lastLoginAt: dateAgoH(3),
    },
    {
      id: USER_BUCH,
      workspaceId: WS_ID,
      name: "Sandra Becker",
      email: "buchhaltung@muellerbau.de",
      role: "user",
      memberRole: "buchhaltung",
      roleLabel: "Buchhaltung",
      hasLicense: true,
      lastLoginAt: dateAgoH(20),
    },
  ]);

  /* ============== PROJEKTE ============== */
  // 4 Projekte über alle Lifecycle-Phasen
  await db.insert(projects).values([
    {
      // 1. Bauphase, kompliziert (Nachträge, BHA, Mängelrüge)
      id: "p_mb_2024_014",
      workspaceId: WS_ID,
      identifier: "BV-2024-014",
      name: "Schulzentrum Lüdenscheid",
      ag: "Stadt Lüdenscheid",
      value: 4_200_000,
      status: "Bauphase",
      progress: 0.62,
      contractType: "vob_vertrag",
      contractDate: "2024-03-15",
      plannedCompletion: "2026-09-30",
      siteAddress: "Schulzentrum, Loher Str. 30, 58507 Lüdenscheid",
      lat: 51.219,
      lon: 7.622,
      penaltyClauseAgreed: true,
      securityRetentionPercent: 5,
      isBauleistung: true,
      notes: "Großprojekt — laufende Nachtragsverhandlungen mit AG.",
    },
    {
      // 2. Bauphase mittlere Größe (Mängelrüge AG, Bedenken)
      id: "p_mb_2025_008",
      workspaceId: WS_ID,
      identifier: "BV-2025-008",
      name: "Wohnanlage Hauptstraße 12 Köln",
      ag: "Demo Wohnbau GmbH",
      value: 1_800_000,
      status: "Bauphase",
      progress: 0.34,
      contractType: "bgb_werkvertrag",
      contractDate: "2025-02-01",
      plannedCompletion: "2026-12-15",
      siteAddress: "Hauptstr. 12, 50667 Köln",
      lat: 50.937,
      lon: 6.96,
      penaltyClauseAgreed: false,
      isBauleistung: true,
    },
    {
      // 3. Gewährleistung — abgeschlossen, anstehende Verjährung
      id: "p_mb_2023_031",
      workspaceId: WS_ID,
      identifier: "BV-2023-031",
      name: "Bahnhof Aachen Sanierung",
      ag: "Demo Verkehrsbetrieb GmbH",
      value: 8_500_000,
      status: "Gewährleistung",
      progress: 1.0,
      contractType: "vob_vertrag",
      contractDate: "2022-06-15",
      plannedCompletion: "2024-08-30",
      abnahmeDate: "2024-09-15",
      warrantyEnd: "2028-09-15",
      siteAddress: "Bahnhofplatz 1, 52064 Aachen",
      lat: 50.768,
      lon: 6.091,
      penaltyClauseAgreed: true,
      securityRetentionPercent: 5,
      isBauleistung: true,
    },
    {
      // 4. Geplant — Vergabe gerade unterzeichnet
      id: "p_mb_2026_002",
      workspaceId: WS_ID,
      identifier: "BV-2026-002",
      name: "Logistikhalle Duisburg-Süd",
      ag: "Demo Logistik AG",
      value: 6_800_000,
      status: "Geplant",
      progress: 0.05,
      contractType: "vob_vertrag",
      contractDate: isoPlus(-14),
      plannedCompletion: "2027-08-31",
      siteAddress: "Industriegebiet Süd, Wanheimer Str. 320, 47053 Duisburg",
      lat: 51.408,
      lon: 6.755,
      penaltyClauseAgreed: true,
      securityRetentionPercent: 5,
      isBauleistung: true,
      notes: "Auftrag frisch unterzeichnet — Vorbereitung Bauanlauf.",
    },
  ]);

  /* ============== KONTAKTE ============== */
  await db.insert(projectContacts).values([
    // BV-2024-014 Schulzentrum
    { id: "pc_mb_014_ag", workspaceId: WS_ID, projectId: "p_mb_2024_014", role: "ag_vertreter", name: "Frau Schmitz", organization: "Stadt Lüdenscheid · Hochbauamt", email: "f.schmitz@demo-stadt.example", phone: "+49 2351 17-2402" },
    { id: "pc_mb_014_arch", workspaceId: WS_ID, projectId: "p_mb_2024_014", role: "architekt", name: "Dr.-Ing. Werner Lehmann", organization: "Demo Architekten GbR", email: "kontakt@demo-architekten.example", phone: "+49 2351 39102" },
    { id: "pc_mb_014_bl", workspaceId: WS_ID, projectId: "p_mb_2024_014", role: "bauleiter_ag", name: "Markus Petersen", organization: "Stadt Lüdenscheid · Bauleitung", email: "m.petersen@demo-stadt.example", phone: "+49 2351 17-2418" },
    { id: "pc_mb_014_anwalt", workspaceId: WS_ID, projectId: "p_mb_2024_014", role: "anwalt", name: "RAin Demo", organization: "Demo Kanzlei für Baurecht", email: "info@demo-kanzlei.example", phone: "+49 221 78934-0" },
    // BV-2025-008 Wohnanlage Köln
    { id: "pc_mb_008_ag", workspaceId: WS_ID, projectId: "p_mb_2025_008", role: "ag_vertreter", name: "Bernd Köhler", organization: "Demo Wohnbau GmbH", email: "b.koehler@demo-wohnbau.example", phone: "+49 221 4567-110" },
    { id: "pc_mb_008_arch", workspaceId: WS_ID, projectId: "p_mb_2025_008", role: "architekt", name: "Architektin Vogt", organization: "Demo Architekturbüro", email: "info@demo-architekturbuero.example", phone: "+49 221 56789" },
    // BV-2023-031 Bahnhof Aachen — Gewährleistung
    { id: "pc_mb_031_ag", workspaceId: WS_ID, projectId: "p_mb_2023_031", role: "ag_vertreter", name: "Holger Weidmann", organization: "Demo Verkehrsbetrieb GmbH", email: "kontakt@demo-verkehr.example", phone: "+49 30 297-12345" },
    // BV-2026-002 Logistikhalle
    { id: "pc_mb_002_ag", workspaceId: WS_ID, projectId: "p_mb_2026_002", role: "ag_vertreter", name: "Sabine Fischer", organization: "Demo Logistik AG", email: "s.fischer@demo-logistik.example", phone: "+49 211 6909-200" },
    { id: "pc_mb_002_fp", workspaceId: WS_ID, projectId: "p_mb_2026_002", role: "fachplaner", name: "TGA-Planer Eberhardt", organization: "Eberhardt + Partner Ingenieure", email: "info@demo-tga-planer.example", phone: "+49 211 4502" },
  ]);

  /* ============== VERTRÄGE ============== */
  await db.insert(contracts).values([
    {
      id: "ct_mb_014_haupt",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Hauptvertrag VOB/B — Schulzentrum Lüdenscheid",
      kind: "hauptvertrag",
      contractText: "Ausführung der Bauleistungen für das Schulzentrum Lüdenscheid gemäß LV vom 12.02.2024. VOB/B ist Vertragsbestandteil. Vertragsstrafe 0,2 % je Werktag bis 5 % der Auftragssumme. Sicherheitseinbehalt 5 %.",
      signedAt: "2024-03-15",
      partyAg: "Stadt Lüdenscheid",
      partyAn: "Müller Bau GmbH",
      riskScore: 38,
      riskFindings: JSON.stringify([
        { level: "medium", title: "Vertragsstrafe-Klausel grenzwertig", basis: "BGH VII ZR 65/14", snippet: "0,2 % je Werktag — Höchstgrenze 5 % AGB-konform; einzeln prüfen." },
      ]),
    },
    {
      id: "ct_mb_014_buer",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Vertragserfüllungsbürgschaft — Hauptvertrag",
      kind: "buergschaft",
      contractText: "Vertragserfüllungsbürgschaft 5 % der Auftragssumme = 210.000 EUR. Avalkredit Commerzbank Köln, Bürgschaftsnr. CB-2024-0411.",
      signedAt: "2024-03-20",
      riskScore: 15,
    },
    {
      id: "ct_mb_008_haupt",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      title: "BGB-Werkvertrag Wohnanlage Hauptstraße 12",
      kind: "hauptvertrag",
      contractText: "BGB-Werkvertrag über die Errichtung der Wohnanlage. § 650a-i BGB. Keine Vertragsstrafe vereinbart.",
      signedAt: "2025-02-01",
      partyAg: "Demo Wohnbau GmbH",
      partyAn: "Müller Bau GmbH",
      riskScore: 24,
    },
    {
      id: "ct_mb_031_haupt",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      title: "VOB/B-Vertrag Bahnhof Aachen",
      kind: "hauptvertrag",
      contractText: "Bauleistung Sanierung Bahnhof Aachen. VOB/B. Sicherheitseinbehalt 5 %.",
      signedAt: "2022-06-15",
      partyAg: "Demo Verkehrsbetrieb GmbH",
      partyAn: "Müller Bau GmbH",
      riskScore: 22,
    },
    {
      id: "ct_mb_002_haupt",
      workspaceId: WS_ID,
      projectId: "p_mb_2026_002",
      title: "Hauptvertrag VOB/B — Logistikhalle Duisburg",
      kind: "hauptvertrag",
      contractText: "VOB/B-Vertrag mit Pauschal-Anteilen + EP für TGA. Vertragsstrafe 0,15 % je Werktag.",
      signedAt: isoPlus(-14),
      partyAg: "Demo Logistik AG",
      partyAn: "Müller Bau GmbH",
      riskScore: 31,
    },
  ]);

  /* ============== NACHUNTERNEHMER ============== */
  await db.insert(subcontractors).values([
    {
      id: "nu_mb_estrich",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      name: "Estrich Bauer",
      organization: "Estrich Bauer GmbH",
      gewerk: "Estricharbeiten",
      contractValue: 145_000,
      contractType: "vob_vertrag",
      passThroughStatus: "klausel_vorhanden",
      ustId: "DE283456789",
      freistellungsbescheinigungNr: "FBS-FA-Köln-2024-1102",
      freistellungsbescheinigungGueltigBis: "2027-03-31",
      email: "info@demo-estrich.example",
      phone: "+49 221 78921",
    },
    {
      id: "nu_mb_tga",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      name: "TGA Schwarz",
      organization: "Schwarz Heizung & Klima GmbH",
      gewerk: "TGA / Heizung-Lüftung",
      contractValue: 380_000,
      contractType: "vob_vertrag",
      passThroughStatus: "klausel_fehlend",
      paymentReleaseBlocked: true,
      ustId: "DE291112233",
      // Freistellung abgelaufen — triggert Compliance-Lücke
      freistellungsbescheinigungNr: "FBS-FA-DU-2023-2204",
      freistellungsbescheinigungGueltigBis: "2025-12-31",
      riskNotes: "Pass-Through-Klausel fehlt im NU-Vertrag · Zahlungsfreigabe gesperrt bis Klärung.",
      email: "info@demo-tga.example",
      phone: "+49 203 9890",
    },
    {
      id: "nu_mb_putz",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      name: "Putz & Stuck Klein",
      organization: "Putz & Stuck Klein GmbH",
      gewerk: "Putzarbeiten · Innen/Außen",
      contractValue: 95_000,
      contractType: "bgb_werkvertrag",
      passThroughStatus: "klausel_vorhanden",
      ustId: "DE251098765",
      freistellungsbescheinigungNr: "FBS-FA-Köln-2025-0411",
      freistellungsbescheinigungGueltigBis: isoPlus(60),
      email: "info@demo-putz.example",
    },
    {
      id: "nu_mb_dach",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      name: "Dachdeckerei Weber",
      organization: "Weber GmbH & Co. KG",
      gewerk: "Dachdeckung · Bauwerksabdichtung",
      contractValue: 410_000,
      contractType: "vob_vertrag",
      passThroughStatus: "klausel_vorhanden",
      email: "office@demo-dach.example",
    },
    // Ausländischer NU für A1-Demo
    {
      id: "nu_mb_metall",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      name: "Kowalski Metallbau",
      organization: "Kowalski Metalowe Sp. z o.o.",
      gewerk: "Stahlbau / Treppen",
      contractValue: 78_000,
      contractType: "vob_vertrag",
      isForeign: true,
      passThroughStatus: "nicht_geprueft",
      ustId: "PL5251234567",
      email: "info@demo-metal.example",
    },
  ]);

  await db.insert(subcontractorCertificates).values([
    // Estrich Bauer — komplett
    { id: "ct_nu_estrich_freist", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "freistellung_48b", issuer: "Finanzamt Köln-Süd", issuedAt: "2024-04-01", validUntil: "2027-03-31", status: "gueltig" },
    { id: "ct_nu_estrich_kk", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "unbedenklich_kk", issuer: "AOK Rheinland", issuedAt: isoPlus(-30), validUntil: isoPlus(60), status: "gueltig" },
    { id: "ct_nu_estrich_bg", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "bg_bau", issuer: "BG BAU", issuedAt: isoPlus(-25), validUntil: isoPlus(65), status: "gueltig" },
    { id: "ct_nu_estrich_soka", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "soka_bau", issuer: "SOKA-Bau", issuedAt: isoPlus(-30), validUntil: isoPlus(60), status: "gueltig" },
    { id: "ct_nu_estrich_milog", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "mindestlohn", issuer: "Eigenerklärung", issuedAt: "2024-04-01", validUntil: "2027-04-01", status: "gueltig" },
    { id: "ct_nu_estrich_gewerbe", workspaceId: WS_ID, subcontractorId: "nu_mb_estrich", kind: "gewerbeanmeldung", issuer: "Stadt Köln", issuedAt: "2018-03-15", validUntil: "2030-12-31", status: "gueltig" },
    // TGA Schwarz — Freistellung ABGELAUFEN, KK fehlt
    { id: "ct_nu_tga_freist", workspaceId: WS_ID, subcontractorId: "nu_mb_tga", kind: "freistellung_48b", issuer: "Finanzamt Duisburg", issuedAt: "2023-04-01", validUntil: "2025-12-31", status: "abgelaufen" },
    { id: "ct_nu_tga_bg", workspaceId: WS_ID, subcontractorId: "nu_mb_tga", kind: "bg_bau", issuer: "BG BAU", issuedAt: isoPlus(-60), validUntil: isoPlus(30), status: "gueltig" },
    // Putz Klein — komplett
    { id: "ct_nu_putz_freist", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "freistellung_48b", issuer: "Finanzamt Köln-Mitte", issuedAt: isoPlus(-300), validUntil: isoPlus(60), status: "gueltig" },
    { id: "ct_nu_putz_kk", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "unbedenklich_kk", issuer: "Techniker Krankenkasse", issuedAt: isoPlus(-15), validUntil: isoPlus(75), status: "gueltig" },
    { id: "ct_nu_putz_bg", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "bg_bau", issuer: "BG BAU", issuedAt: isoPlus(-15), validUntil: isoPlus(75), status: "gueltig" },
    { id: "ct_nu_putz_soka", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "soka_bau", issuer: "SOKA-Bau", issuedAt: isoPlus(-15), validUntil: isoPlus(75), status: "gueltig" },
    { id: "ct_nu_putz_milog", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "mindestlohn", issuer: "Eigenerklärung", issuedAt: isoPlus(-200), validUntil: isoPlus(165), status: "gueltig" },
    { id: "ct_nu_putz_gewerbe", workspaceId: WS_ID, subcontractorId: "nu_mb_putz", kind: "gewerbeanmeldung", issuer: "Stadt Köln", issuedAt: "2010-09-01", validUntil: "2030-12-31", status: "gueltig" },
    // Dachdeckerei Weber — Gewährleistungs-Projekt, alle aktuell
    { id: "ct_nu_dach_freist", workspaceId: WS_ID, subcontractorId: "nu_mb_dach", kind: "freistellung_48b", issuer: "Finanzamt Aachen", issuedAt: "2024-01-15", validUntil: "2027-01-15", status: "gueltig" },
    { id: "ct_nu_dach_bg", workspaceId: WS_ID, subcontractorId: "nu_mb_dach", kind: "bg_bau", issuer: "BG BAU", issuedAt: isoPlus(-45), validUntil: isoPlus(45), status: "gueltig" },
    // Kowalski — A1 + Mindestlohn-Eigenerklärung, KK fehlt (A1 deckt nur Sozialversicherung im Heimatland)
    { id: "ct_nu_metall_a1", workspaceId: WS_ID, subcontractorId: "nu_mb_metall", kind: "a1_entsendung", issuer: "ZUS Polen", issuedAt: isoPlus(-30), validUntil: isoPlus(335), status: "gueltig" },
    { id: "ct_nu_metall_milog", workspaceId: WS_ID, subcontractorId: "nu_mb_metall", kind: "mindestlohn", issuer: "Eigenerklärung", issuedAt: isoPlus(-30), validUntil: isoPlus(335), status: "gueltig" },
  ]);

  /* ============== NACHTRÄGE ============== */
  await db.insert(nachtraege).values([
    {
      id: "nt_mb_014_tuer",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Türmodell DIN 18101 → DIN 18101-XL (Möbeltransport)",
      description: "AG-Anordnung Frau Schmitz vom Vortag — Türen breiter wegen Möbeltransport. 24 Türen × 350 EUR Mehrkosten + Stahlzargen-Anpassung.",
      value: 8_400,
      legalBasis: "§ 2 Abs. 5 VOB/B",
      status: "angekuendigt",
      trigger: "anordnung_ag",
      announcedAt: isoPlus(-1),
    },
    {
      id: "nt_mb_014_estrich",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Heizestrich-Stärke 65 → 80 mm (Bodenaufbau-Anpassung)",
      description: "Statiker fordert dickeren Estrich wegen Punktlasten Möbel-Aufstellung Klassenräume. Mengenmehrung 240 m².",
      value: 11_500,
      legalBasis: "§ 2 Abs. 6 VOB/B",
      status: "eingereicht",
      trigger: "bauseits_geaendert",
      announcedAt: isoPlus(-25),
      submittedAt: isoPlus(-12),
    },
    {
      id: "nt_mb_014_fenster",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Fensterprofile auf U-Wert 0,9 verbessert",
      description: "AG wünscht KfW-55-Standard nachträglich. Fenster auf 3-fach-Verglasung mit U=0,9.",
      value: 23_800,
      legalBasis: "§ 2 Abs. 5 VOB/B",
      status: "anerkannt",
      trigger: "anordnung_ag",
      announcedAt: isoPlus(-90),
      submittedAt: isoPlus(-75),
      decidedAt: isoPlus(-45),
    },
    {
      id: "nt_mb_008_tuermodell",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      title: "Wohnungseingangstüren auf Schallschutzklasse 4 (statt 3)",
      description: "Auf Wunsch der Mieter — Schallschutzklasse 4 statt vereinbarte 3.",
      value: 6_200,
      legalBasis: "§ 2 Abs. 5 VOB/B",
      status: "entwurf",
      trigger: "anordnung_ag",
    },
    {
      id: "nt_mb_008_putz",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      title: "Putzaufbau Treppenhaus — Sanierungsputz wegen Untergrund",
      description: "Untergrund poröser als kalkuliert — Sanierungsputz statt Standardputz.",
      value: 4_650,
      legalBasis: "§ 2 Abs. 6 VOB/B",
      status: "eingereicht",
      trigger: "bauseits_geaendert",
      announcedAt: isoPlus(-3),
      submittedAt: isoPlus(-1),
    },
  ]);

  /* ============== SICHERHEITEN ============== */
  await db.insert(securities).values([
    {
      id: "sec_mb_014_vert",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      kind: "vertragserfuellung",
      direction: "provided_to_ag",
      provider: "Commerzbank Köln",
      referenceNumber: "CB-2024-0411",
      amount: 210_000,
      percentOfContract: 5,
      issuedAt: "2024-03-20",
      validFrom: "2024-03-20",
      releaseTrigger: "bei_abnahme",
      status: "aktiv",
    },
    {
      id: "sec_mb_014_bareinbehalt",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      kind: "bareinbehalt",
      direction: "provided_to_ag",
      provider: "Bareinbehalt durch AG (Stadt Lüdenscheid)",
      amount: 87_400,
      percentOfContract: 2.08,
      releaseTrigger: "bei_gewaehrleistungsende",
      status: "aktiv",
      notes: "Wachsender Einbehalt aus laufenden Abschlagsrechnungen.",
    },
    {
      id: "sec_mb_031_maeng",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      kind: "maengelanspruch",
      direction: "provided_to_ag",
      provider: "Allianz Trade",
      referenceNumber: "AT-2024-9817",
      amount: 425_000,
      percentOfContract: 5,
      issuedAt: "2024-09-15",
      validFrom: "2024-09-15",
      validUntil: "2028-09-15",
      releaseTrigger: "bei_gewaehrleistungsende",
      status: "aktiv",
    },
    {
      id: "sec_mb_002_vert",
      workspaceId: WS_ID,
      projectId: "p_mb_2026_002",
      kind: "vertragserfuellung",
      direction: "provided_to_ag",
      provider: "Commerzbank Köln",
      referenceNumber: "CB-2026-0021",
      amount: 340_000,
      percentOfContract: 5,
      issuedAt: isoPlus(-7),
      validFrom: isoPlus(-7),
      releaseTrigger: "bei_abnahme",
      status: "aktiv",
    },
    {
      id: "sec_mb_008_buerg",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      kind: "bauhandwerker",
      direction: "received_from_ag",
      provider: "Sparkasse KölnBonn",
      referenceNumber: "SK-2025-1144",
      amount: 540_000,
      percentOfContract: 30,
      issuedAt: "2025-02-10",
      validFrom: "2025-02-10",
      releaseTrigger: "manuell",
      status: "aktiv",
      notes: "Bauhandwerkersicherung gem. § 650f BGB — wir als AN haben sie eingefordert.",
    },
  ]);

  /* ============== FRISTEN ============== */
  await db.insert(fristen).values([
    { id: "f_mb_001", workspaceId: WS_ID, projectId: "p_mb_2024_014", task: "BHA versenden — fehlende TGA-Pläne (Klimazentrale 2.OG)", deadline: isoPlus(1), legalBasis: "§ 6 Abs. 1 VOB/B" },
    { id: "f_mb_002", workspaceId: WS_ID, projectId: "p_mb_2025_008", task: "Mangelrüge AG beantworten — Putz-Risse Treppenhaus", deadline: isoPlus(3), legalBasis: "§ 13 Abs. 5 VOB/B" },
    { id: "f_mb_003", workspaceId: WS_ID, projectId: "p_mb_2025_008", task: "Nachtragsangebot Türmodell DIN 18101 erstellen", deadline: isoPlus(5), legalBasis: "§ 2 Abs. 6 VOB/B" },
    { id: "f_mb_004", workspaceId: WS_ID, projectId: "p_mb_2023_031", task: "Verjährungsablauf Gewährleistung — Sichtbeton Halle 3", deadline: isoPlus(14), legalBasis: "§ 13 Abs. 4 VOB/B" },
    { id: "f_mb_005", workspaceId: WS_ID, projectId: "p_mb_2024_014", task: "Schlussrechnung BV-2024-014 (Zwischenstand) vorlegen", deadline: isoPlus(28), legalBasis: "§ 14 VOB/B" },
    { id: "f_mb_006", workspaceId: WS_ID, projectId: "p_mb_2024_014", task: "TGA Schwarz: Freistellung erneuern oder Bauabzug einbehalten", deadline: isoPlus(7), legalBasis: "§ 48 EStG" },
    { id: "f_mb_007", workspaceId: WS_ID, projectId: "p_mb_2026_002", task: "Bauanlauf Logistikhalle — Baustelleneinrichtung", deadline: isoPlus(21) },
  ]);

  /* ============== MEILENSTEINE ============== */
  await db.insert(meilensteine).values([
    // BV-2024-014
    { id: "ms_mb_014_1", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "Baustellen-Einrichtung", reihenfolge: 0, sollDatum: "2024-04-15", istDatum: "2024-04-12", status: "erreicht" },
    { id: "ms_mb_014_2", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "Rohbau Halle 1 fertig", reihenfolge: 1, sollDatum: "2024-09-30", istDatum: "2024-10-04", status: "erreicht" },
    { id: "ms_mb_014_3", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "Dichtigkeit Dach", reihenfolge: 2, sollDatum: "2025-03-15", istDatum: "2025-03-10", status: "erreicht" },
    { id: "ms_mb_014_4", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "TGA Klimazentrale 2.OG fertig", reihenfolge: 3, sollDatum: isoPlus(45), status: "verzoegert", verzoegerungGrund: "Plan-Verzug Architekt → BHA versendet (§ 6 Abs. 1 VOB/B)" },
    { id: "ms_mb_014_5", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "Innenausbau abgeschlossen", reihenfolge: 4, sollDatum: "2026-04-30", status: "geplant" },
    { id: "ms_mb_014_6", workspaceId: WS_ID, projectId: "p_mb_2024_014", bezeichnung: "Förmliche Abnahme", reihenfolge: 5, sollDatum: "2026-09-30", status: "geplant" },
    // BV-2025-008
    { id: "ms_mb_008_1", workspaceId: WS_ID, projectId: "p_mb_2025_008", bezeichnung: "Rohbau-Beginn", reihenfolge: 0, sollDatum: "2025-04-01", istDatum: "2025-04-01", status: "erreicht" },
    { id: "ms_mb_008_2", workspaceId: WS_ID, projectId: "p_mb_2025_008", bezeichnung: "Putz Treppenhaus", reihenfolge: 1, sollDatum: isoPlus(-5), status: "laufend" },
    { id: "ms_mb_008_3", workspaceId: WS_ID, projectId: "p_mb_2025_008", bezeichnung: "Innenausbau Wohnungen", reihenfolge: 2, sollDatum: "2026-08-31", status: "geplant" },
    { id: "ms_mb_008_4", workspaceId: WS_ID, projectId: "p_mb_2025_008", bezeichnung: "Fertigstellung", reihenfolge: 3, sollDatum: "2026-12-15", status: "geplant" },
    // BV-2026-002
    { id: "ms_mb_002_1", workspaceId: WS_ID, projectId: "p_mb_2026_002", bezeichnung: "Erdarbeiten / Aushub", reihenfolge: 0, sollDatum: isoPlus(28), status: "geplant" },
    { id: "ms_mb_002_2", workspaceId: WS_ID, projectId: "p_mb_2026_002", bezeichnung: "Bodenplatte fertig", reihenfolge: 1, sollDatum: isoPlus(95), status: "geplant" },
    { id: "ms_mb_002_3", workspaceId: WS_ID, projectId: "p_mb_2026_002", bezeichnung: "Stahlbau Hallenkonstruktion", reihenfolge: 2, sollDatum: isoPlus(180), status: "geplant" },
    { id: "ms_mb_002_4", workspaceId: WS_ID, projectId: "p_mb_2026_002", bezeichnung: "Förmliche Abnahme", reihenfolge: 3, sollDatum: "2027-08-31", status: "geplant" },
  ]);

  /* ============== BAUTAGEBUCH ============== */
  await db.insert(bautagebuchEntries).values([
    {
      id: "bt_mb_001",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(0),
      category: "anordnung",
      text: 'Frau Schmitz vom AG ruft an: möchte Türmodell von DIN 18101 auf eine breitere Variante (DIN 18101-XL) ändern wegen Möbeltransport. Sagt: „machen Sie das mal". Habe zugesagt.',
      weatherCondition: "bewoelkt",
      temperatureCelsius: 14,
      staffHoursOwn: 64,
      staffHoursSubcontractors: 16,
      equipment: "1× Bagger, 1× Kran 25 t",
      trigger: "anordnung",
      triggerLabel: "Anordnung erkannt",
      urgency: "critical",
      suggestion: "§ 2 Abs. 5 Mehrkosten-Ankündigung VOR Ausführung — sonst Anspruchsverlust",
      createdAt: dateAgoH(2),
    },
    {
      id: "bt_mb_002",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(0),
      category: "behinderung",
      text: "TGA-Pläne 2.OG noch nicht eingegangen. Habe nachgefragt — Architekt sagt nächste Woche.",
      weatherCondition: "bewoelkt",
      temperatureCelsius: 14,
      trigger: "behinderung",
      triggerLabel: "Mögliche Behinderung",
      urgency: "warning",
      suggestion: "Plan-Anforderung schriftlich · bei Verzug >5 Tage BHA versenden",
      createdAt: dateAgoH(5),
    },
    {
      id: "bt_mb_003",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(-1),
      category: "bedenken",
      text: 'Untergrund Treppenhaus für Putz: Altanstrich nicht vollständig entfernt, sehr porös. Anweisung von AG: „einfach drüber putzen".',
      weatherCondition: "regen",
      temperatureCelsius: 9,
      staffHoursOwn: 24,
      equipment: "1× Hubarbeitsbühne",
      trigger: "bedenken",
      triggerLabel: "Bedenken-Trigger",
      urgency: "critical",
      suggestion: "§ 4 Abs. 3 Bedenkenanmeldung sofort schriftlich",
      createdAt: dateAgo(1),
    },
    {
      id: "bt_mb_004",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(-1),
      category: "behinderung",
      text: "Witterung: Dauerregen seit 3 Tagen, Estrich-Arbeiten Halle 1 nicht möglich. DWD prognostiziert weitere 2 Tage Regen.",
      weatherCondition: "regen",
      temperatureCelsius: 8,
      weatherPrecipitationMm: 28,
      weatherSource: "api",
      weatherFetchedAt: dateAgo(1),
      staffHoursOwn: 0,
      equipment: "Estrichmaschine vorgehalten",
      trigger: "behinderung",
      triggerLabel: "Witterungs-Behinderung",
      urgency: "warning",
      suggestion: "BHA mit DWD-Wetterbericht für Bauzeitverlängerung",
      createdAt: dateAgo(1),
    },
    {
      id: "bt_mb_005",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      authorId: USER_GF,
      authorName: "T. Müller",
      entryDate: isoPlus(-2),
      category: "besichtigung",
      text: "Begehung mit AG-Vertreter Frau Schmitz und Architekt Lehmann. Bautagebuch geprüft, Soll-Ist-Termine besprochen.",
      weatherCondition: "sonnig",
      temperatureCelsius: 18,
      urgency: "info",
      createdAt: dateAgo(2),
    },
    {
      id: "bt_mb_006",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(-6),
      category: "mangel",
      text: "AG hat Mangelrüge per Brief geschickt — Putz-Risse Treppenhaus 1.OG. Frist 5 Tage.",
      weatherCondition: "sonnig",
      temperatureCelsius: 16,
      trigger: "mangelruege",
      triggerLabel: "Eingehende Mangelrüge",
      urgency: "critical",
      suggestion: "Sofort Rüge-Analyse-Modul öffnen — Frist zu kurz",
      createdAt: dateAgo(6),
    },
    {
      id: "bt_mb_007",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      authorId: USER_POLIER,
      authorName: "K. Schmidt",
      entryDate: isoPlus(-3),
      category: "personal",
      text: "Personalstand heute: 8 eigene MA, 6 NU Estrich Bauer (Halle 2), 4 NU TGA Schwarz (Heizung Erdgeschoss).",
      weatherCondition: "bewoelkt",
      temperatureCelsius: 12,
      staffHoursOwn: 64,
      staffHoursSubcontractors: 80,
      urgency: "info",
      createdAt: dateAgo(3),
    },
  ]);

  /* ============== ANZEIGEN (BHA + Bedenken) ============== */
  await db.insert(anzeigen).values([
    {
      id: "az_mb_014_bha_tga",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      kind: "behinderung",
      status: "versendet",
      title: "Behinderungsanzeige — Fehlende TGA-Pläne 2. OG Klimazentrale",
      subjectMatter: "TGA-Pläne 2. OG für die Klimazentrale liegen seit 14 Tagen nicht vor. Estrich-Vorbereitung 2. OG kann nicht starten.",
      bodyMarkdown: "Sehr geehrter Herr Lehmann,\n\nhiermit zeigen wir gemäß § 6 Abs. 1 VOB/B eine Behinderung unserer Bauausführung an.\n\n**Sachverhalt:** Die Ausführungspläne TGA für die Klimazentrale 2. OG liegen uns trotz Aufforderung vom 12.04. weiterhin nicht vor. Ohne diese Pläne kann der Estricheinbau im 2. OG nicht beginnen.\n\n**Voraussichtliche Dauer:** ca. 10 Werktage je weitere Woche Plan-Verzug.\n\n**Mehrkosten:** ca. 4.800 EUR/Woche (Vorhaltekosten Estrichmaschine, Personalumdisposition).\n\nWir bitten um umgehende Bereitstellung der Pläne sowie Bestätigung dieser Anzeige.\n\nMit freundlichen Grüßen\nThomas Müller",
      legalBasis: "§ 6 Abs. 1 VOB/B",
      recipientName: "Dr.-Ing. Werner Lehmann",
      recipientEmail: "kontakt@demo-architekten.example",
      recipientRole: "architekt",
      obstructionStart: isoPlus(-14),
      estimatedDurationDays: 10,
      estimatedExtraCost: 4_800,
      causedBy: "fehlende_plaene",
      sentAt: isoPlus(-7),
      sourceBautagebuchEntryId: "bt_mb_002",
    },
    {
      id: "az_mb_008_bedenken",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      kind: "bedenken",
      status: "versendet",
      title: "Bedenkenanmeldung — Poröser Untergrund Treppenhaus",
      subjectMatter: "Untergrund Treppenhaus 1. OG ist deutlich poröser als kalkuliert; standardmäßiger Putz wird nicht haften.",
      bodyMarkdown: "Sehr geehrter Herr Köhler,\n\nhiermit melden wir gemäß § 4 Abs. 3 VOB/B Bedenken an.\n\n**Sachverhalt:** Bei Vorbereitung des Putzauftrags Treppenhaus haben wir festgestellt, dass der Altanstrich nicht vollständig entfernt wurde und der Untergrund stark porös ist. Standardputz wird mit hoher Wahrscheinlichkeit Risse bilden oder abblättern.\n\n**Mögliche Folgen:** Putzschäden, Mängelrügen, Nachbesserungsaufwand.\n\n**Vorschlag:** Wir empfehlen einen Sanierungsputz statt des vereinbarten Standardputzes. Mehrkosten ca. 4.650 EUR netto.\n\nWir bitten um schriftliche Stellungnahme bis Freitag.\n\nMit freundlichen Grüßen\nThomas Müller",
      legalBasis: "§ 4 Abs. 3 VOB/B",
      recipientName: "Bernd Köhler",
      recipientEmail: "b.koehler@demo-wohnbau.example",
      recipientRole: "ag_vertreter",
      concernAbout: "vorleistung",
      potentialDamage: "Putzrisse / Putzabplatzungen / Mängelrügen",
      proposedSolution: "Sanierungsputz statt Standardputz, Mehrkosten 4.650 EUR netto",
      sentAt: isoPlus(-2),
      sourceBautagebuchEntryId: "bt_mb_003",
    },
  ]);

  /* ============== MÄNGEL (über alle Phasen) ============== */
  await db.insert(maengel).values([
    {
      id: "ma_mb_008_putzrisse",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      phase: "ausfuehrung",
      kategorie: "Putz · Treppenhaus",
      beschreibung: "Putz-Risse Treppenhaus 1. OG, Länge ca. 80 cm, Breite 0,3 mm. AG verlangt Nachbesserung mit Frist 5 Tage.",
      ortImBauwerk: "Treppenhaus 1. OG, Wand Süd",
      gemeldetVon: "Demo Wohnbau GmbH (B. Köhler)",
      gemeldetAm: isoPlus(-6),
      status: "strittig",
      prioritaet: "hoch",
      fristsetzungDatum: isoPlus(3),
      kostenGeschaetztCents: eur(2_400),
      notes: "Untergrund-Vorleistung war porös (siehe Bedenkenanzeige) — Mitverschulden AG.",
    },
    {
      id: "ma_mb_031_sichtbeton",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      phase: "gewaehrleistung",
      kategorie: "Sichtbeton · Halle 3",
      beschreibung: "Verfärbungen + Aussinterungen am Sichtbeton Halle 3, Westfassade. Vom AG nach 12 Monaten Nutzung gerügt.",
      ortImBauwerk: "Halle 3, Westfassade EG-1.OG",
      gemeldetVon: "Demo Verkehrsbetrieb GmbH (H. Weidmann)",
      gemeldetAm: isoPlus(-30),
      status: "in_bearbeitung",
      prioritaet: "mittel",
      fristsetzungDatum: isoPlus(14),
      behebungBis: isoPlus(45),
      kostenGeschaetztCents: eur(8_500),
    },
    {
      id: "ma_mb_014_estrich",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      phase: "ausfuehrung",
      kategorie: "Estrich · Halle 1",
      beschreibung: "Vereinzelte Hohlstellen im Estrich Halle 1, Bereich 12 m². NU Estrich Bauer hat Nacharbeit zugesagt.",
      ortImBauwerk: "Halle 1 nördlicher Bereich",
      gemeldetVon: "Eigene Bauleitung (K. Schmidt)",
      gemeldetAm: isoPlus(-15),
      status: "in_bearbeitung",
      prioritaet: "niedrig",
      behebungBis: isoPlus(10),
      kostenGeschaetztCents: eur(1_200),
      behobenDurchNuId: "nu_mb_estrich",
    },
    {
      id: "ma_mb_031_dachan",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      phase: "abnahme",
      kategorie: "Dachanschluss · Halle 1",
      beschreibung: "Bei Abnahme festgestellt: Dichtigkeit Dachanschluss Halle 1 nicht durchgängig. Vorbehalt im Abnahmeprotokoll.",
      ortImBauwerk: "Halle 1 Dach Nord",
      gemeldetVon: "DB-Bauleitung",
      gemeldetAm: "2024-09-15",
      status: "behoben",
      prioritaet: "hoch",
      behobenAm: "2024-10-08",
      kostenGeschaetztCents: eur(4_800),
      kostenIstCents: eur(5_120),
      behobenDurchNuId: "nu_mb_dach",
    },
  ]);

  await db.insert(maengelAnzeigen).values([
    {
      id: "maa_mb_008_putzrisse_antwort",
      workspaceId: WS_ID,
      mangelId: "ma_mb_008_putzrisse",
      versendetAm: isoPlus(-1),
      versandweg: "email",
      inhaltText: "Sehr geehrter Herr Köhler, wir nehmen Ihre Mangelrüge zu den Putz-Rissen ernst. Die von Ihnen gesetzte Frist von 5 Tagen ist gem. § 13 Abs. 5 VOB/B / BGH VII ZR 13/16 nicht angemessen. Wir bieten Nachbesserung in 14 Werktagen ab gemeinsamer Beweissicherung an, vorbehaltlich der Kostentragung (Vorleistung war porös, siehe unsere Bedenkenanmeldung).",
      anzeigeAnExtern: "Bernd Köhler · Demo Wohnbau GmbH · b.koehler@demo-wohnbau.example",
    },
  ]);

  /* ============== ABNAHMEN ============== */
  await db.insert(abnahmen).values([
    {
      id: "ab_mb_031",
      workspaceId: WS_ID,
      projectId: "p_mb_2023_031",
      kind: "foermlich",
      abnahmeDate: "2024-09-15",
      abnahmeOrt: "Bahnhof Aachen, Bahnhofplatz 1",
      gesamtbeurteilung: "mit_unwesentlichen_maengeln",
      attendees: JSON.stringify([
        { name: "Thomas Müller", role: "AN-Geschäftsleitung", signed: true },
        { name: "Holger Weidmann", role: "AG-Bauleitung DB", signed: true },
        { name: "Dr.-Ing. Albers", role: "Architekt", signed: true },
      ]),
      vertragsstrafeAgreed: true,
      vertragsstrafeReserved: true,
      vertragsstrafeReservationText: "Die Geltendmachung einer Vertragsstrafe wegen 14-tägiger Bauzeit-Überschreitung wird hiermit ausdrücklich vorbehalten.",
      handoverComplete: true,
      notes: "Mängel-Vorbehalt: Dachanschluss Halle 1 (siehe Mangel-Akte). Behebung bis 31.10. zugesagt.",
    },
  ]);

  /* ============== AUSGANGSRECHNUNGEN ============== */
  await db.insert(ausgangsrechnungen).values([
    {
      id: "ar_mb_014_a1",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      number: "AR-2024-0001",
      kind: "abschlag",
      abschlagNo: 1,
      invoiceDate: "2024-06-15",
      dueDate: "2024-07-15",
      partyAg: "Stadt Lüdenscheid",
      partyAn: "Müller Bau GmbH",
      partyAnTaxId: "000/0000/0001",
      partyAnVatId: "DE100000001",
      vatPercent: 0,
      reverseCharge: true,
      reverseChargeGrund: "Bauleistung an öffentlichen AG nach § 13b UStG",
      previousAbschlaegeNet: 0,
      securityRetentionPercent: 5,
      securityRetentionAmount: 22_500,
      totalPositionsNet: 450_000,
      payoutNet: 427_500,
      payoutVat: 0,
      payoutGross: 427_500,
      status: "bezahlt",
      sentAt: new Date("2024-06-16"),
      paidAt: new Date("2024-07-12"),
      paidAmount: 427_500,
    },
    {
      id: "ar_mb_014_a2",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      number: "AR-2024-0002",
      kind: "abschlag",
      abschlagNo: 2,
      invoiceDate: "2024-09-10",
      dueDate: "2024-10-10",
      partyAg: "Stadt Lüdenscheid",
      partyAn: "Müller Bau GmbH",
      vatPercent: 0,
      reverseCharge: true,
      reverseChargeGrund: "§ 13b UStG",
      previousAbschlaegeNet: 450_000,
      securityRetentionPercent: 5,
      securityRetentionAmount: 31_250,
      totalPositionsNet: 625_000,
      payoutNet: 593_750,
      payoutGross: 593_750,
      status: "bezahlt",
      sentAt: new Date("2024-09-11"),
      paidAt: new Date("2024-10-08"),
      paidAmount: 593_750,
    },
    {
      id: "ar_mb_014_a3",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      number: "AR-2025-0006",
      kind: "abschlag",
      abschlagNo: 3,
      invoiceDate: isoPlus(-30),
      dueDate: isoPlus(0),
      partyAg: "Stadt Lüdenscheid",
      partyAn: "Müller Bau GmbH",
      vatPercent: 0,
      reverseCharge: true,
      reverseChargeGrund: "§ 13b UStG",
      previousAbschlaegeNet: 1_075_000,
      securityRetentionPercent: 5,
      securityRetentionAmount: 33_750,
      totalPositionsNet: 675_000,
      payoutNet: 641_250,
      payoutGross: 641_250,
      status: "mahnung_1",
      sentAt: dateAgo(28),
    },
    {
      id: "ar_mb_008_a1",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      number: "AR-2025-0011",
      kind: "abschlag",
      abschlagNo: 1,
      invoiceDate: isoPlus(-21),
      dueDate: isoPlus(9),
      partyAg: "Demo Wohnbau GmbH",
      partyAn: "Müller Bau GmbH",
      vatPercent: 19,
      reverseCharge: false,
      previousAbschlaegeNet: 0,
      totalPositionsNet: 184_000,
      payoutNet: 184_000,
      payoutVat: 34_960,
      payoutGross: 218_960,
      status: "versendet",
      sentAt: dateAgo(19),
    },
  ]);

  await db.insert(ausgangsrechnungPositionen).values([
    { id: "arp_mb_014_a3_p1", workspaceId: WS_ID, ausgangsrechnungId: "ar_mb_014_a3", sortIndex: 0, oz: "01.10", description: "Rohbau Halle 1 — Wandkonstruktion (Teilleistung Mai)", quantity: 1, unit: "psch", unitPrice: 380_000, totalPrice: 380_000 },
    { id: "arp_mb_014_a3_p2", workspaceId: WS_ID, ausgangsrechnungId: "ar_mb_014_a3", sortIndex: 1, oz: "12.10.20", description: "Heizestrich CT-C25-F4 Halle 1, 65 mm", quantity: 6_500, unit: "m²", unitPrice: 38, totalPrice: 247_000 },
    { id: "arp_mb_014_a3_p3", workspaceId: WS_ID, ausgangsrechnungId: "ar_mb_014_a3", sortIndex: 2, oz: "07.40", description: "Innentüren-Lieferung Vorab Halle 1", quantity: 24, unit: "Stk", unitPrice: 2_000, totalPrice: 48_000 },
    { id: "arp_mb_008_a1_p1", workspaceId: WS_ID, ausgangsrechnungId: "ar_mb_008_a1", sortIndex: 0, oz: "01.10", description: "Rohbau-Beginn Hauptstraße 12 — Bodenplatte + EG-Wände", quantity: 1, unit: "psch", unitPrice: 184_000, totalPrice: 184_000 },
  ]);

  await db.insert(ausgangsrechnungMahnungen).values([
    {
      id: "mahn_mb_014_a3_1",
      workspaceId: WS_ID,
      ausgangsrechnungId: "ar_mb_014_a3",
      level: 1,
      issuedAt: isoPlus(-2),
      dueDate: isoPlus(12),
      mahngebuehr: 5,
      verzugszinsen: 312.45,
      zinsSatzPercent: 8,
      zinsBasisBetrag: 641_250,
      zinsTage: 14,
      sentAt: dateAgo(2),
    },
  ]);

  /* ============== EINGANGSRECHNUNGEN (mit Anomalien) ============== */
  await db.insert(rechnungen).values([
    {
      id: "rg_mb_estrich_apr",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      subcontractorId: "nu_mb_estrich",
      supplierName: "Estrich Bauer GmbH",
      invoiceDate: isoPlus(-30),
      dueDate: isoPlus(0),
      totalNet: 18_500,
      totalGross: 22_015,
      currency: "EUR",
      status: "geprueft",
      uploadedBy: USER_BUCH,
      uploadedAt: dateAgo(28),
      anomalyScore: 0,
      anomalyCount: 0,
    },
    {
      id: "rg_mb_estrich_mai",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      subcontractorId: "nu_mb_estrich",
      supplierName: "Estrich Bauer GmbH",
      invoiceDate: isoPlus(-3),
      dueDate: isoPlus(27),
      totalNet: 21_750,
      totalGross: 25_882.5,
      currency: "EUR",
      status: "eingegangen",
      uploadedBy: USER_BUCH,
      uploadedAt: dateAgo(2),
      anomalyScore: 66,
      anomalyCount: 4,
    },
    {
      id: "rg_mb_putz_apr",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      subcontractorId: "nu_mb_putz",
      supplierName: "Putz & Stuck Klein GmbH",
      invoiceDate: isoPlus(-5),
      dueDate: isoPlus(25),
      totalNet: 4_650,
      totalGross: 5_533.5,
      currency: "EUR",
      status: "eingegangen",
      uploadedBy: USER_BUCH,
      uploadedAt: dateAgo(4),
      anomalyScore: 12,
      anomalyCount: 1,
    },
    // TGA Schwarz — mit BAUABZUG (Freistellung abgelaufen) → für ELSTER-Demo
    {
      id: "rg_mb_tga_mai",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      subcontractorId: "nu_mb_tga",
      supplierName: "Schwarz Heizung & Klima GmbH",
      invoiceDate: isoPlus(-4),
      dueDate: isoPlus(26),
      totalNet: 35_000,
      totalGross: 41_650,
      currency: "EUR",
      status: "eingegangen",
      uploadedBy: USER_BUCH,
      uploadedAt: dateAgo(3),
      bauabzugEinbehaltCents: eur(6_247.5),
      anomalyScore: 0,
      anomalyCount: 0,
    },
  ]);

  await db.insert(rechnungPositionen).values([
    // April-Rechnung (sauber)
    { id: "rp_mb_a1", rechnungId: "rg_mb_estrich_apr", positionIndex: 0, lvPosition: "12.10.20", description: "Heizestrich CT-C25-F4 Halle 1, 65 mm", quantity: 420, unit: "m²", unitPrice: 38, totalPrice: 15_960 },
    { id: "rp_mb_a2", rechnungId: "rg_mb_estrich_apr", positionIndex: 1, lvPosition: "12.10.30", description: "Randdämmstreifen 8 mm", quantity: 280, unit: "m", unitPrice: 9.07, totalPrice: 2_540 },
    // Mai-Rechnung (mit Anomalien)
    { id: "rp_mb_m1", rechnungId: "rg_mb_estrich_mai", positionIndex: 0, lvPosition: "12.10.20", description: "Heizestrich CT-C25-F4 Halle 1, 65 mm", quantity: 460, unit: "m²", unitPrice: 47, totalPrice: 21_620 },
    { id: "rp_mb_m2", rechnungId: "rg_mb_estrich_mai", positionIndex: 1, lvPosition: "12.10.30", description: "Randdämmstreifen 8 mm", quantity: 310, unit: "m", unitPrice: 9.07, totalPrice: 2_811.7 },
    { id: "rp_mb_m3", rechnungId: "rg_mb_estrich_mai", positionIndex: 2, lvPosition: "99.99.99", description: "Sonderaufwand Wochenendarbeit", quantity: 4, unit: "Std", unitPrice: 95, totalPrice: 420 },
    { id: "rp_mb_p1", rechnungId: "rg_mb_putz_apr", positionIndex: 0, lvPosition: "08.40.10", description: "Innenputz Q2 Treppenhaus", quantity: 95, unit: "m²", unitPrice: 32, totalPrice: 3_040 },
    { id: "rp_mb_p2", rechnungId: "rg_mb_putz_apr", positionIndex: 1, lvPosition: "08.40.95", description: "Zuschlag Anschluss Bestand (nicht im LV)", quantity: 1, unit: "psch", unitPrice: 1_610, totalPrice: 1_610 },
  ]);

  await db.insert(rechnungAnomalien).values([
    { id: "ra_mb_m_jump", rechnungId: "rg_mb_estrich_mai", kind: "price_jump", severity: "warning", description: "LV-Position 12.10.20: Einheitspreis 47,00 € liegt 24 % über dem Vorrechnungs-Mittel (38,00 €).", payloadJson: JSON.stringify({ lvPosition: "12.10.20", currentPrice: 47, avgPrevious: 38, deltaPercent: 24 }), resolved: false },
    { id: "ra_mb_m_math", rechnungId: "rg_mb_estrich_mai", kind: "math_error", severity: "critical", description: "Position 3: 4 × 95,00 € ergibt 380,00 € — ausgewiesen 420,00 €.", payloadJson: JSON.stringify({ expected: 380, actual: 420, positionIndex: 2 }), resolved: false },
    { id: "ra_mb_m_notc", rechnungId: "rg_mb_estrich_mai", kind: "not_in_contract", severity: "warning", description: "LV-Position 99.99.99 im Hauptvertrag nicht gefunden — möglicherweise Nachtragspflicht.", payloadJson: JSON.stringify({ lvPosition: "99.99.99" }), resolved: false },
    { id: "ra_mb_p_notc", rechnungId: "rg_mb_putz_apr", kind: "not_in_contract", severity: "warning", description: "LV-Position 08.40.95 im Hauptvertrag nicht gefunden — möglicherweise Nachtragspflicht.", payloadJson: JSON.stringify({ lvPosition: "08.40.95" }), resolved: false },
  ]);

  /* ============== MITARBEITER + STUNDEN ============== */
  await db.insert(mitarbeiter).values([
    { id: "ma_mb_klaus", workspaceId: WS_ID, name: "Klaus Schmidt", personalnummer: "MB-002", lohnart: "monat", monatsgehaltCents: eur(5_400), kostenstelle: "Bauleitung", gewerk: "Polier", eintrittDatum: "2018-04-01", aktiv: true },
    { id: "ma_mb_jurgen", workspaceId: WS_ID, name: "Jürgen Hoffmann", personalnummer: "MB-014", lohnart: "stunden", stundensatzCents: eur(28), kostenstelle: "Rohbau", gewerk: "Maurer", eintrittDatum: "2020-03-15", aktiv: true },
    { id: "ma_mb_dimitri", workspaceId: WS_ID, name: "Dimitri Petrov", personalnummer: "MB-021", lohnart: "stunden", stundensatzCents: eur(26), kostenstelle: "Rohbau", gewerk: "Eisenflechter", eintrittDatum: "2021-08-01", aktiv: true },
    { id: "ma_mb_anna", workspaceId: WS_ID, name: "Anna Walter", personalnummer: "MB-023", lohnart: "stunden", stundensatzCents: eur(24), kostenstelle: "Innenausbau", gewerk: "Maler", eintrittDatum: "2022-05-01", aktiv: true },
  ]);

  // Letzte Woche an Stunden für 2 MA × 5 Tage
  const stundenInserts: typeof stunden.$inferInsert[] = [];
  const days = [-6, -5, -4, -3, -2];
  for (const d of days) {
    stundenInserts.push({
      id: `st_mb_klaus_${d}`,
      workspaceId: WS_ID,
      mitarbeiterId: "ma_mb_klaus",
      projektId: "p_mb_2024_014",
      datum: isoPlus(d),
      stunden: 8,
      taetigkeit: "Bauleitung Schulzentrum",
      stundensatzCents: eur(5_400 / 173.33),
    });
    stundenInserts.push({
      id: `st_mb_jurgen_${d}`,
      workspaceId: WS_ID,
      mitarbeiterId: "ma_mb_jurgen",
      projektId: "p_mb_2024_014",
      datum: isoPlus(d),
      stunden: 8,
      taetigkeit: "Mauerwerk Halle 2",
      stundensatzCents: eur(28),
    });
    stundenInserts.push({
      id: `st_mb_dimitri_${d}`,
      workspaceId: WS_ID,
      mitarbeiterId: "ma_mb_dimitri",
      projektId: "p_mb_2024_014",
      datum: isoPlus(d),
      stunden: 8,
      taetigkeit: "Bewehrung Halle 2 OG",
      stundensatzCents: eur(26),
    });
    stundenInserts.push({
      id: `st_mb_anna_${d}`,
      workspaceId: WS_ID,
      mitarbeiterId: "ma_mb_anna",
      projektId: "p_mb_2025_008",
      datum: isoPlus(d),
      stunden: 8,
      taetigkeit: "Spachtelarbeiten Treppenhaus",
      stundensatzCents: eur(24),
    });
  }
  await db.insert(stunden).values(stundenInserts);

  /* ============== SACHVERSTÄNDIGE ============== */
  await db.insert(sachverstaendige).values([
    {
      id: "sv_mb_008_putz",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      anlass: "maengelstreit",
      fragestellung: "Sind die Putzrisse auf mangelhafte Vorleistung des AG (poröser Untergrund) oder fehlerhafte AN-Ausführung zurückzuführen? Welcher Anteil ist welchem Verursacher zuzuordnen?",
      rechtsgrundlage: "paragraph_485_zpo",
      sachverstaendigerName: "Dipl.-Ing. Friedrich Voss",
      sachverstaendigerOrganization: "ÖbVI Voss · Bausachverstand",
      sachverstaendigerEmail: "voss@bausv-voss.de",
      sachverstaendigerPhone: "+49 221 89234",
      kostenGeschaetztCents: eur(3_500),
      kostenTraeger: "streit",
      status: "angefragt",
    },
  ]);

  /* ============== VORGÄNGE ============== */
  await db.insert(vorgaenge).values([
    {
      id: "vg_mb_ruege_putz",
      workspaceId: WS_ID,
      projectId: "p_mb_2025_008",
      title: "Mängelrüge AG · Putz-Risse Treppenhaus 1.OG",
      category: "maengelruege",
      status: "in_bearbeitung",
      riskScore: 78,
      createdBy: USER_GF,
      assignedTo: USER_GF,
      dueDate: isoPlus(3),
      createdAt: dateAgo(6),
      updatedAt: dateAgo(1),
    },
    {
      id: "vg_mb_anordnung_tuer",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "AG-Anordnung Türmodell DIN 18101 → 18101-XL · Mehrkosten ankündigen",
      category: "vertragspflicht",
      status: "offen",
      riskScore: 65,
      createdBy: USER_GF,
      dueDate: isoPlus(2),
      createdAt: dateAgo(1),
      updatedAt: dateAgo(1),
    },
    {
      id: "vg_mb_bha_tga",
      workspaceId: WS_ID,
      projectId: "p_mb_2024_014",
      title: "Behinderungsanzeige · TGA-Pläne 2.OG seit 2 Wochen ausstehend",
      category: "vertragspflicht",
      status: "wartet_auf_anwalt",
      riskScore: 82,
      createdBy: USER_POLIER,
      assignedTo: USER_GF,
      dueDate: isoPlus(1),
      createdAt: dateAgo(12),
      updatedAt: dateAgo(2),
    },
  ]);

  await db.insert(vorgangDocuments).values([
    { id: "vd_mb_ruege_brief", vorgangId: "vg_mb_ruege_putz", fileName: "Mangelruege_AG_Koeln_Wohnen.pdf", mimeType: "application/pdf", fileSize: 142_336, storagePath: "storage/seed/vg_mb_ruege_putz/Mangelruege_AG_Koeln_Wohnen.pdf", uploadedBy: USER_GF, uploadedAt: dateAgo(6) },
    { id: "vd_mb_anordnung_email", vorgangId: "vg_mb_anordnung_tuer", fileName: "Email_Schmitz_Tuermodell_XL.eml", mimeType: "message/rfc822", fileSize: 8_192, storagePath: "storage/seed/vg_mb_anordnung_tuer/Email_Schmitz_Tuermodell_XL.eml", uploadedBy: USER_GF, uploadedAt: dateAgo(1) },
  ]);

  await db.insert(vorgangAnalysisSteps).values([
    {
      id: "vs_mb_ruege_klass",
      vorgangId: "vg_mb_ruege_putz",
      stepIndex: 0,
      kind: "klassifikation",
      payloadJson: JSON.stringify({ category: "maengelruege", confidence: 0.85, matchedTerms: ["mängel", "nachbesserung", "risse"] }),
      citations: JSON.stringify([{ kind: "vob", ref: "§ 13 Abs. 5 VOB/B", snippet: "Mangelbeseitigung mit angemessener Frist" }]),
      createdAt: dateAgo(6),
    },
    {
      id: "vs_mb_ruege_recherche",
      vorgangId: "vg_mb_ruege_putz",
      stepIndex: 1,
      kind: "recherche",
      payloadJson: JSON.stringify({ summary: "Frist von 5 Tagen ist nicht angemessen — BGH VII ZR 13/16 fordert mindestens 10 Werktage." }),
      citations: JSON.stringify([{ kind: "urteil", ref: "BGH VII ZR 13/16" }, { kind: "bgb", ref: "§ 634a BGB" }]),
      createdAt: dateAgo(5),
    },
    {
      id: "vs_mb_anordnung_klass",
      vorgangId: "vg_mb_anordnung_tuer",
      stepIndex: 0,
      kind: "klassifikation",
      payloadJson: JSON.stringify({ category: "vertragspflicht", confidence: 0.7, matchedTerms: ["anordnung", "vertrag"] }),
      citations: JSON.stringify([{ kind: "vob", ref: "§ 2 Abs. 5 VOB/B" }]),
      createdAt: dateAgo(1),
    },
  ]);

  await db.insert(vorgangCitations).values([
    { id: "vc_mb_1", vorgangId: "vg_mb_ruege_putz", sourceKind: "vob", sourceRef: "§ 13 Abs. 5 VOB/B", sourceText: "Mangelbeseitigung mit angemessener Frist." },
    { id: "vc_mb_2", vorgangId: "vg_mb_ruege_putz", sourceKind: "urteil", sourceRef: "BGH VII ZR 13/16", sourceText: "Angemessene Frist regelmäßig 10 Werktage." },
    { id: "vc_mb_3", vorgangId: "vg_mb_anordnung_tuer", sourceKind: "vob", sourceRef: "§ 2 Abs. 5 VOB/B", sourceText: "Mehrkosten-Ankündigung VOR Ausführung." },
    { id: "vc_mb_4", vorgangId: "vg_mb_bha_tga", sourceKind: "vob", sourceRef: "§ 6 Abs. 1 VOB/B", sourceText: "Behinderungsanzeige formal an AG." },
  ]);

  await db.insert(vorgangDrafts).values([
    {
      id: "vdr_mb_ruege_antwort",
      vorgangId: "vg_mb_ruege_putz",
      kind: "email",
      recipientEmail: "b.koehler@demo-wohnbau.example",
      subject: "Ihre Mängelrüge — Antwort & angemessene Frist",
      bodyMarkdown: "Sehr geehrter Herr Köhler,\n\nvielen Dank für Ihr Schreiben. Wir nehmen Ihre Mangelrüge zu den Putz-Rissen ernst.\n\nDie von Ihnen gesetzte Frist von 5 Tagen ist gemäß § 13 Abs. 5 VOB/B nicht angemessen (vgl. BGH VII ZR 13/16). Wir bieten Nachbesserung **innerhalb von 14 Werktagen ab Beweissicherungstermin** an, **vorbehaltlich der Kostentragung**.\n\nMit freundlichen Grüßen\nThomas Müller",
      status: "entwurf",
      createdAt: dateAgo(4),
      updatedAt: dateAgo(1),
    },
    {
      id: "vdr_mb_anordnung_mehrkosten",
      vorgangId: "vg_mb_anordnung_tuer",
      kind: "email",
      recipientEmail: "f.schmitz@demo-stadt.example",
      subject: "Anordnung Türmodell DIN 18101-XL · Mehrkosten-Ankündigung § 2 Abs. 5 VOB/B",
      bodyMarkdown: "Sehr geehrte Frau Schmitz,\n\nbezugnehmend auf Ihren Anruf bestätigen wir Ihre Anordnung, das Türmodell von DIN 18101 auf DIN 18101-XL zu ändern.\n\nWir kündigen Ihnen hiermit gemäß § 2 Abs. 5 VOB/B Mehrkosten in Höhe von ca. 8.400 EUR netto an. Die Ausführung erfolgt ausschließlich nach schriftlicher Bestätigung.\n\nMit freundlichen Grüßen\nThomas Müller",
      status: "entwurf",
      createdAt: dateAgo(1),
      updatedAt: dateAgo(1),
    },
  ]);

  await db.insert(vorgangLinks).values([
    { id: "vl_mb_1", vorgangId: "vg_mb_ruege_putz", targetKind: "bautagebuch", targetId: "bt_mb_003", createdAt: dateAgo(4) },
    { id: "vl_mb_2", vorgangId: "vg_mb_ruege_putz", targetKind: "frist", targetId: "f_mb_002", createdAt: dateAgo(5) },
    { id: "vl_mb_3", vorgangId: "vg_mb_anordnung_tuer", targetKind: "bautagebuch", targetId: "bt_mb_001", createdAt: dateAgo(1) },
    { id: "vl_mb_4", vorgangId: "vg_mb_anordnung_tuer", targetKind: "frist", targetId: "f_mb_003", createdAt: dateAgo(1) },
    { id: "vl_mb_5", vorgangId: "vg_mb_bha_tga", targetKind: "frist", targetId: "f_mb_001", createdAt: dateAgo(12) },
    { id: "vl_mb_6", vorgangId: "vg_mb_bha_tga", targetKind: "bautagebuch", targetId: "bt_mb_002", createdAt: dateAgo(12) },
  ]);

  await db.insert(vorgangAuditLog).values([
    { id: "au_mb_1", vorgangId: "vg_mb_ruege_putz", actorId: USER_GF, action: "created", payloadJson: JSON.stringify({ title: "Mängelrüge AG · Putz-Risse Treppenhaus" }), createdAt: dateAgo(6) },
    { id: "au_mb_2", vorgangId: "vg_mb_ruege_putz", actorId: USER_GF, action: "document_uploaded", payloadJson: JSON.stringify({ fileName: "Mangelruege_AG_Koeln_Wohnen.pdf" }), createdAt: dateAgo(6) },
    { id: "au_mb_3", vorgangId: "vg_mb_ruege_putz", actorId: USER_GF, action: "status_changed", payloadJson: JSON.stringify({ from: "offen", to: "in_bearbeitung" }), createdAt: dateAgo(5) },
    { id: "au_mb_4", vorgangId: "vg_mb_anordnung_tuer", actorId: USER_GF, action: "created", payloadJson: JSON.stringify({ title: "AG-Anordnung Türmodell" }), createdAt: dateAgo(1) },
    { id: "au_mb_5", vorgangId: "vg_mb_bha_tga", actorId: USER_GF, action: "status_changed", payloadJson: JSON.stringify({ from: "in_bearbeitung", to: "wartet_auf_anwalt" }), createdAt: dateAgo(2) },
  ]);

  /* ============== ANFRAGEN-HISTORIE ============== */
  await db.insert(queries).values([
    { id: "q_mb_001", workspaceId: WS_ID, userId: USER_GF, question: "AG fordert 8 % Vertragsstrafe — wirksam?", category: "Vertragsstrafe", createdAt: dateAgoH(2) },
    { id: "q_mb_002", workspaceId: WS_ID, userId: USER_GF, question: "Behinderungsanzeige für TGA-Plan-Verzug", category: "Behinderung", createdAt: dateAgo(1) },
    { id: "q_mb_003", workspaceId: WS_ID, userId: USER_GF, question: "§ 13 Abs. 5 VOB/B — Frist Mangelbeseitigung", category: "Mängel", createdAt: dateAgo(2) },
    { id: "q_mb_004", workspaceId: WS_ID, userId: USER_GF, question: "Sicherheitseinbehalt 10 % — Bürgschaft anbieten?", category: "Sicherheiten", createdAt: dateAgo(3) },
    { id: "q_mb_005", workspaceId: WS_ID, userId: USER_BUCH, question: "Bauabzug bei NU-Rechnung ohne Freistellung — wann anmelden?", category: "Steuer", createdAt: dateAgo(4) },
  ]);

  console.log("  ✓ Müller Bau: 4 Projekte · 5 NU + 17 Cert · 5 Nachträge · 5 Sicherheiten · 4 Mängel · 7 Bautagebuch · 14 Meilensteine · 4 ARs · 4 Eingangsrg · 4 MA + 20 Stundensätze · 3 Vorgänge · 1 SV-Akte");
}
